/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : Time,
});
export const RosterMember = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'avatarUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addOrUpdateRosterMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllRosterMembers' : IDL.Func([], [IDL.Vec(RosterMember)], ['query']),
  'removeAnnouncement' : IDL.Func([IDL.Text], [], []),
  'removeRosterMember' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : Time,
  });
  const RosterMember = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addOrUpdateRosterMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllRosterMembers' : IDL.Func([], [IDL.Vec(RosterMember)], ['query']),
    'removeAnnouncement' : IDL.Func([IDL.Text], [], []),
    'removeRosterMember' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };